name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull
       
        run: |
          - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          - echo "Deploying the PROD project..."
          - ssh -tt -o StrictHostKeyChecking=no $SSH_HOST \ 
          "cd /path/to/project-folder/ && git reset --hard && git pull"
          - echo "Deploying the ci cd ana anaaa..."
